spring:
  application:
    name: eureka-server

server:
  port: 8000

eureka:
  server:
#  关闭注册中心节点保护机制
    enable-self-preservation: false
  instance:
#    prefer-ip-address: true
    hostname: localhost
  client:
#  关闭自我注册
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    healthcheck:
      enabled: true