#spring:
#  application:
#    name: eureka-server

server:
  port: 8002

eureka:
  server:
#  关闭注册中心节点保护机制
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
#    hostname: peer2
  client:
#  打开自我注册
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka